##########
# DO NOT RENAME THIS FILE TO CONFIGURATION.YAML! YOU WILL BREAK YOUR CONFIG IF YOU DO SO!
# INSTEAD, COPY THIS CODE WITHIN YOUR OWN CONFIGURATION.YAML          
##########

#sensors
sensor:

##########
# Mailbox Sensor          
##########
  - platform: template
    sensors:
      mailbox_last_triggered_formatted:
        friendly_name: Mailbox Last triggered
        value_template: >-
          {% if (
              (( as_timestamp(now()) | timestamp_custom("%m%d")) | int) - ((as_timestamp(states("input_datetime.mailbox_last_triggered")) | timestamp_custom("%m%d")) | int)
              ) == 0 %}
            {{ as_timestamp(states("input_datetime.mailbox_last_triggered")) | timestamp_custom("%H:%M") }}
          {% else %}
            none
          {% endif %}