##########
# DO NOT RENAME THIS FILE TO CUSTOMIZE.YAML! YOU WILL BREAK YOUR CONFIG IF YOU DO SO!
# INSTEAD, COPY THIS CODE WITHIN YOUR OWN CUSTOMIZE.YAML          
##########

sensor.afvalwijzer_today:
  friendly_name: Vandaag
sensor.afvalwijzer_tomorrow:
  friendly_name: Morgen
sensor.afvalwijzer_first_next_item:
  friendly_name: Next pickup item
sensor.afvalwijzer_first_next_in_days:
  friendly_name: Next pickup in days
input_boolean.afvalwijzer_reminder:
  icon: mdi:reminder

sensor.afvalwijzer_gft:
  friendly_name: GFT
  entity_picture: /local/afvalwijzer/gft.png
sensor.afvalwijzer_papier:
  friendly_name: Papier
  entity_picture: /local/afvalwijzer/papier.png
sensor.afvalwijzer_restafval:
  friendly_name: Restafval
  entity_picture: /local/afvalwijzer/restafval.png
sensor.afvalwijzer_pmd:
  friendly_name: PMD
  entity_picture: /local/afvalwijzer/pmd.png
