##########
# DO NOT RENAME THIS FILE TO CUSTOMIZE.YAML!
# COPY THIS CODE WITHIN YOUR OWN CUSTOMIZE.YAML          
##########

sensor.trash_today:
  friendly_name: Vandaag
sensor.trash_tomorrow:
  friendly_name: Morgen
sensor.trash_first_next_item:
  friendly_name: Next pickup item
sensor.trash_first_next_in_days:
  friendly_name: Next pickup in days
input_boolean.trash_reminder:
  icon: mdi:reminder

sensor.trash_gft_afval:
  friendly_name: GFT
  entity_picture: /local/afvalwijzer/gft.png
sensor.trash_papier:
  friendly_name: Papier
  entity_picture: /local/afvalwijzer/papier.png
sensor.trash_restafval:
  friendly_name: Restafval
  entity_picture: /local/afvalwijzer/restafval.png
