##########
# DO NOT RENAME THIS FILE TO CONFIGURATION.YAML! YOU WILL BREAK YOUR CONFIG IF YOU DO SO!
# INSTEAD, COPY THIS CODE WITHIN YOUR OWN SECRETS.YAML          
##########

mariadb_url: 'mysql://yourusername:yourpassword@core-mariadb/homeassistant?charset=utf8'